package main

import (
	"github.com/ozgen/goreportx/internal/models"
	"github.com/ozgen/goreportx/internal/renderer"
	"github.com/ozgen/goreportx/internal/renderer/json"
	"github.com/ozgen/goreportx/internal/renderer/pdf"
	"html/template"
	"log"
	"path/filepath"

	"github.com/ozgen/goreportx/examples/common"
)

func main() {
	// Load logo and wrap
	logoBase64 := renderer.LoadImageBase64("assets/logo.png")
	logoHTML := renderer.WrapLogoAsHTML(logoBase64, renderer.AlignCenter)
	footerHeaderBase64 := renderer.LoadImageBase64("assets/header_footer.png")

	// Create charts
	charts := []models.Chart{
		{
			Title:       "Usage Overview",
			Description: "Chart showing daily user activity.",
			Tag:         renderer.WrapChartAsHTML(common.GenerateChartBase64(), renderer.AlignCenter),
			Order:       0,
		},
		{
			Title:       "Error Trends",
			Description: "Error spikes across regions.",
			Tag:         renderer.WrapChartAsHTML(common.GenerateChartBase64(), renderer.AlignRight),
			Order:       1,
		},
	}

	// Create report model
	report := models.Report{
		Header: models.Header{
			Title:       "Basic Report Example",
			Subtitle:    "Auto-generated by GoReportX",
			Explanation: "This report demonstrates basic rendering features.",
			Logo:        logoHTML,
		},
		Footer: models.Footer{
			Note: "Generated by GoReportX • All rights reserved.",
		},
		Data: map[string]string{
			"Customer": "Jane Doe",
			"Email":    "jane@example.com",
			"Project":  "AI Insights",
			"Status":   "Completed",
		},
		Charts: charts,
	}

	// Load template
	tmplPath := filepath.Join("internal", "template", "defaults", "smart_template_new.html")
	tmpl, err := template.ParseFiles(tmplPath)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	// Render PDF
	pdfRenderer := pdf.NewPDFRenderer(report, tmpl, common.DefaultFontSizes, true, "", footerHeaderBase64, footerHeaderBase64)
	_, err = pdfRenderer.Render("examples/outputs/output-basic.pdf")
	if err != nil {
		log.Fatalf("Failed to render PDF: %v", err)
	}
	log.Println("PDF saved to output-basic.pdf")

	// Render JSON
	jsonRenderer := json.NewJSONRenderer(report)
	_, err = jsonRenderer.Render("examples/outputs/output-basic.json")
	if err != nil {
		log.Fatalf("Failed to render JSON: %v", err)
	}
	log.Println("JSON saved to output-basic.json")
}
